plugins {
	id 'maven-publish'
	id 'dev.architectury.loom-no-remap' version "${loom_version}" apply false
	id 'architectury-plugin' version "${architectury_version}"
	id "base"
}

allprojects {
	version = project.mod_version
	group = project.maven_group
}

architectury {
	minecraft = project.minecraft_version
}

subprojects {
	apply plugin: 'dev.architectury.loom-no-remap'
	apply plugin: 'architectury-plugin'
	apply plugin: 'maven-publish'

	base {
		archivesName = "$rootProject.archives_base_name-$project.name"
	}

	repositories {
		// Add repositories to retrieve artifacts from in here.
		// You should only use this when depending on other mods because
		// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
		// See https://docs.gradle.org/current/userguide/declaring_repositories.html
		// for more information about repositories.
	}


	dependencies {
		// To change the versions see the gradle.properties file
		minecraft "com.mojang:minecraft:${project.minecraft_version}"
//	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
		implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"


	}

	processResources {
		inputs.property "version", project.version

		filesMatching("fabric.mod.json") {
			expand "version": project.version
		}
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 25
	}

	java {
		// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
		// if it is present.
		// If you remove this line, sources will not be generated.
		withSourcesJar()

		sourceCompatibility = JavaVersion.VERSION_25
		targetCompatibility = JavaVersion.VERSION_25
	}

	jar {
		def projectName = project.name
		inputs.property "projectName", projectName

		from("LICENSE") {
			rename { "${it}_$projectName" }
		}
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 25
	}

// configure the maven publication
	publishing {
		publications {
			create("mavenJava", MavenPublication) {
				artifactId = project.archives_base_name
				from components.java
			}
		}

		// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
		repositories {

		}
	}
}


tasks.register("multiplatform", Jar) {
	archiveClassifier.set("universal")

	from project(":common").sourceSets.main.output
	from project(":fabric").sourceSets.main.output
	from project(":neoforge").sourceSets.main.output

	duplicatesStrategy = DuplicatesStrategy.EXCLUDE

	dependsOn(
			":common:classes",
			":fabric:classes",
			":neoforge:classes"
	)
}

tasks.named("build") {
	dependsOn("multiplatform")
}