# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true



group=com.emeraldingot.demo
java_version=25
version=6.0.0

# Common
minecraft_version=26.1
mod_name=Demo
mod_author=EmeraldIngot
mod_id=demo
license=GPL-3.0-Only
credits=
description="Wait, I thought I paid for Minecraft!"
minecraft_version_range=[26.1, 26.3]

neo_form_version=26.1-1


# Fabric
fabric_loader_version=0.10.7

# NeoForge
neoforge_version=26.1.0.19-beta
neoforge_loader_version_range=[4,)

# Mod Properties
maven_group=com.emeraldingot.demo
archives_base_name=demo-26.1-26.3