# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Architectury Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
architectury_version=3.5-SNAPSHOT
enabled_platforms = fabric,neoforge


# Fabric
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# NeoForge
neoforge_version=26.2.0.69

# Mod Properties
mod_version=5.0.0
maven_group=com.emeraldingot.demo
archives_base_name=demo-26.2
mod_id=demo