license="GPL-3.0"

[[mods]]

modId="demo"


version="5.0.0"

# A display name for the mod
displayName="Demo Mod"
iconFile="assets/demo/icon.png"

authors="EmeraldIngot64"

description='''
Wait, I thought I payed for Minecraft!
'''

[[mixins]]
config="demo.mixins.json"
